# frozen_string_literal: true

brew 'mise'
brew 'curl'
brew 'bash'
brew 'neovim', args: ['HEAD']
brew 'tree-sitter-cli'
brew 'starship'
brew 'moreutils'
brew 'fzy'
brew 'coreutils'
brew 'ffmpeg'
brew 'fd'
brew 'ripgrep'
brew 'git'
brew 'btop'
brew 'gcc'
brew 'imagemagick'
brew 'jq'
brew 'pgcli'
brew 'fzf'
brew 'bat'
brew 'lazygit'
brew 'lazydocker'
brew 'yt-dlp'
brew 'gh'
brew 'koekeishiya/formulae/yabai'
brew 'koekeishiya/formulae/skhd'
brew 'git-delta'
brew 'mkcert'
brew 'awscli'
brew 'libpq'
brew 'direnv'
brew 'duf'
brew 'gdu'
brew 'uv'
brew 'displayplacer'
brew 'llm'
brew 'bandwhich'
brew 'lua-language-server'
brew 'switchaudio-osx'
brew 'default-anton/tap/wt'
brew 'tw93/tap/mole'
brew 'steipete/tap/gifgrep'

cask 'font-fira-code-nerd-font'
cask 'ghostty'
