#!/usr/bin/env bash

brew_packages=$(cat <<EOF
neovim
starship
moreutils
fzy
atool
exiftool
trash-cli
coreutils
nnn
ffmpeg
dep
fd
ripgrep
rclone
tmux
kubectl
doctl
git
git-standup
tig
hub
htop
tree
wget
links
bash-completion@2
bundler-completion
docker-completion
docker-compose
docker-compose-completion
gem-completion
rails-completion
rake-completion
ruby-completion
gcc
imagemagick
jq
ctags
colordiff
fzf
gawk
graphviz
pandoc
the_silver_searcher
ack
terraform
kubernetes-helm
node
pgcli
EOF
)

brew install $brew_packages
