#!/usr/bin/env bash

brew_packages=$(cat <<EOF
neovim
starship
moreutils
fzy
atool
exiftool
coreutils
nnn
ffmpeg
fd
ripgrep
tmux
git
git-standup
tig
htop
tree
wget
bash-completion@2
bundler-completion
docker-completion
docker-compose
gem-completion
rails-completion
rake-completion
ruby-completion
gcc
imagemagick
jq
ctags
colordiff
gawk
graphviz
pandoc
pgcli
nvm
fzf
watch
EOF
)

brew install $brew_packages
