#!/usr/bin/env bash

mkdir ~/Downloads/FiraCode
(
  cd ~/Downloads/FiraCode;
  wget https://github.com/tonsky/FiraCode/releases/download/2/FiraCode_2.zip;
  unzip FiraCode_2.zip;
  cp ttf/*.ttf ~/Library/Fonts/
)
rm -rf ~/Downloads/FiraCode
