#!/usr/bin/env bash

case "$(uname -a)" in
  *microsoft*)
    curl -sLo/tmp/win32yank.zip https://github.com/equalsraf/win32yank/releases/download/v0.0.4/win32yank-x64.zip
    unzip -p /tmp/win32yank.zip win32yank.exe > /tmp/win32yank.exe
    chmod +x /tmp/win32yank.exe
    mv /tmp/win32yank.exe ~/.local/bin/
    ;;&
  Linux*)
    sudo apt install curl python3 python3-pip fonts-firacode
    # nnn dependencies
    sudo apt install patool vlock
    ;;
  Darwin*)
    brew install curl vim bash

    mkdir ~/Downloads/FiraCode
    (
      cd ~/Downloads/FiraCode;
      wget https://github.com/tonsky/FiraCode/releases/download/2/FiraCode_2.zip;
      unzip FiraCode_2.zip;
      cp ttf/*.ttf ~/Library/Fonts/
    )
    rm -rf ~/Downloads/FiraCode
    ;;
  *)
esac
