#!/bin/sh

# Add git branch if relevant
parse_git_branch() {
  git rev-parse --abbrev-ref HEAD
}

# Extact tracker abbreviation and ticket number (e.g. DS-123)
parse_ticket() {
  parse_git_branch | grep --only-matching --regexp '[A-Z]\+-[0-9]\+'
}

MESSAGE="$(cat $1)"
TICKET="$(parse_ticket)"

if [ -n "$TICKET" ]
then
  echo "[$TICKET] $MESSAGE" > $1
fi
